/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  //  */
  docs: [
    'index',
    {
      type: 'category',
      label: 'First Things First',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'installation-v5',
        'creating-a-tardis',
        'companions',
        'artron-energy',
        'enter-and-exit',
        'removing-a-tardis',
      ],
    },
    {
      type: 'category',
      label: 'Time Travelling',
      link: {
        type: 'generated-index',
      },
      items: [
        'time-travel',
        'advanced-console',
        'keyboard',
        'malfunction',
      ],
    },
    {
      type: 'category',
      label: 'Cool Stuff To Do & Use',
      link: {
        type: 'generated-index',
      },
      items: [
        'resource-packs',
        'zero-room',
        'weeping-angels',
        'lazarus',
        'sonic-screwdriver',
        'perception-filter',
        'ars',
        'rooms',
        'gravity-wells',
        'custom-rooms',
        'modifying-the-tardis-interior',
        'desktop-theme',
        'chameleon-circuit',
        'junk-tardis',
        'food',
        'scanner',
        'condenser',
        'artron-cells',
        'farming',
        'hads',
        'emergency-program-one',
        'autonomous',
        'translator',
        'achievements',
        'schematics',
      ],
    },
    {
      type: 'category',
      label: "Commands",
      link: {
        type: "generated-index"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'commands',
        },
      ]
    },
    {
      type: 'category',
      label: 'Admin Stuff',
      link: {
        type: 'generated-index',
      },
      items: [
        'localisation',
        'tips',
        'permissions',
        'kits',
        'recipes',
        'add-permissions',
        'tardis-areas',
        'rooms-and-economies',
      ],
    },
  ],
};

module.exports = sidebars;
